### ISSUE TITLE
Skyshowtime's tile

### ISSUE THREAD

**Issue by Fabrice19730526** [spocky/miproja1#12]
The tile of this application displays as transparent. 
Didn't have this issue in 4.24

**Comment by spocky** [comment]
Before 4.30, Projectivy was using rather complex code to display the different banner sources (apps, channels, now playing...).
This has been greatly simplified in 4.30 (which means fewer potential bugs, easier maintainability, ability to fully leverage the cache system of the lib used to load images). 
Unfortunately, there seems to be a bug in this lib, caused by a very specific configuration of skyshowtime's banner asset.

https://github.com/bumptech/glide/issues/5165

Given the specificity of this issue, I'm not sure it'll ever get fixed. In the meantime, I harcoded a workaround in 4.31. Hopefully not many apps use the same configuration.
