### ISSUE TITLE
RMC BFM Play - ! tiles in the row

### ISSUE THREAD

**Issue by Fabrice19730526** [spocky/miproja1#15]
The tiles populating in that channel row are all with a grey/black background and an exclamation mark.

**Comment by Fabrice19730526** [comment]
Fixed in 4.31
But issue remains with TV Quick Actions created Channel row

**Comment by spocky** [comment]
In 4.30+ (improved in 4.31 and incoming 4.32), if you open the related channel settings, you'll get the error message explaining what's causing the error.
As for "TV Quick Actions", you should see something like this `Can't load pictures. Report this error to TV Quick Actions : "ContentProvider not exported"`.
This means that Tv Quick Actions developer needs to export the ContentProvider, so that 3rd party apps can access it and display pictures (this probably doesn't cause this problem on the stock launcher because it's a system app that has more privileges).
