### ISSUE TITLE
Install older version

### ISSUE THREAD

**Issue by cobch** [spocky/miproja1#28]
Is it possible to rollback to an earlier version? I have some issues and would like to use an older version that was working better instead.

**Comment by spocky** [comment]
Depends on which version you want to install and your current settings. It will be hard to tell.
You'll probably want to export your current settings. Then install the older version. If anything goes wrong (ex: settings lost or incomplete because too many things have changed between both version), you could still reinstall the latest one and restore your settings.

**Comment by cobch** [comment]
Hi,
Sorry for late answer. I have the version 3.25 of project ivory Launcher.

I run it on a Fengmi cinema 4K pro.
Device: Jerry
Model: FMProjA2
Chinese version

**Comment by spocky** [comment]
You can install a previous version of Projectivy. If anything doesn't work as expected, you'll probably need to reset Projectivy settings, though.
