### ISSUE TITLE
Issues with input shortcuts not working

### ISSUE THREAD

**Issue by cobch** [spocky/miproja1#30]
In the newer version of the launcher I got problem with the inputs shortcuts. A message appears  instead of opening the hdmi input as it did before (when CEC is activated)

![image](https://github.com/spocky/miproja1/assets/50397676/98507cf1-c3c5-4d47-b083-258f311d4d06)

![image](https://github.com/spocky/miproja1/assets/50397676/634b997b-2192-4712-b93a-29b65c852c6c)

**Comment by spocky** [comment]
It's a bit surprising as I haven't changed code regarding this feature for a long time.
Could you try to find the latest version where it works as expected on your device ? 
For what I could tell from your screenshots, it rather seems that Es File transfers intercepts this intent instead of the Tv input app. Maybe there's a bug in their code. What happens if you uninstall Es File manager ?

**Comment by cobch** [comment]
Yes, it works when I uninstall ES explorer... but I would like to have this app still. Any idea how to do to change this behaviour?

**Comment by spocky** [comment]
I'm already using the proper intent to open a passthrough input. But ES file explorer, as a multi-purpose app, tries to respond to most intents, just in case, which interfers with the stock input app.
I try to be the most specific I can (not only using the input channel, but also the input app name when I know it, which prevents third party apps from opening the intent). 
Unfortunately, this depends on each OEM implementation. It will get better over time, though, as the next Projectivy release will log passthrough input apps, so that I can add support for them.
