### ISSUE TITLE
Watch next channel hide/remove things

### ISSUE THREAD

**Issue by cremonies** [spocky/miproja1#51]
Is it possible to remove things from the watch next channel?

**Comment by spocky** [comment]
Hi, if you long press a card in the watch next section, you should have an option to "hide" it.
Please note this will not really remove it from watch next like the way it's done on the stock launcher (it means it will still be visible in the stock launcher even if hidden in Projectivy). The reason is only the app that added a watch next card OR system apps have the permissions to remove these cards, is not something Projectivy can request permission for.
