### ISSUE TITLE
Is this project being discontinued?

### ISSUE THREAD

**Issue by cowballz** [spocky/miproja1#54]
Just wondering

**Comment by spocky** [comment]
I've been working on it 2 to 4 hours _every_ night (more during the weekend) for the last 2 years. If anything, it has increased recently.
So I guess it's a no 😉

Just to give you an idea, along with developing new features, due to its increased popularity, I spend much more time on support (emails, forums, issues here...). I'm also rewriting some parts of the code, which have delayed my initial deadline for the new release.

It shouldn't be too far away, though.

![](https://media1.giphy.com/media/7WwVYKDMt5khG/giphy.gif?cid=6c09b952fcu6goo9go0wi7jnoya5ilu5dhlkmzv3xd1ya88i&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=g)
