### ISSUE TITLE
Icons disappear when scrolling down a few categories then repopulate 

### ISSUE THREAD

**Issue by cowballz** [spocky/miproja1#63]
Scrolling is pretty smooth. I have about 19 categories and one thing I noticed is if you scroll up or down fast, the icons will disappear and have to repopulate every time.I have a pretty fast system so I wouldn't need for the icons to be removed from memory.

I believe this is the new feature
"Improved global UI perf and memory usage : scrolling on the launcher should be offer a smoother experience on low end devices"

Can there be a new option in settings to turn that off? and allow the icons to be loaded at all times like before ?

This new feature would absolutely be great only for low end devices 

Thank you 👍👍

**Comment by spocky** [comment]
You're right, that's one of the many things I've done to further improve perfs, but it's the only thing that has some kind of "downside" compared to the previous versions. Even if the UI was already pretty smooth on my Nvidia Shield, I found that this feature could further improve the scrooling experience.

You're wrong on one thing though : even with the previous versions, the categories had to be repopulated (even the best Android Tv devices can't manage that many elements in memory), this is how android "recyclerview" works internally. What is different now is that I prevent it from repopulating while it's scrolling, so that image fetch will only happen when everything is still. This is working fine when you scroll down one row at a time, leaving 1s or so between presses, because a few offscreen rows are already populated. In this configuration you get the best of both worlds : nothing happens when the scrolling is occurring, assuring a really smooth experience and you don't see the rows getting populated because it's done offscreen. Of course, it's when you're scrolling fast that it gets obvious that something changed. 

I will probably add a toggle in the settings.

**Comment by cowballz** [comment]
You're 100% correct. It's only when you scroll fast. However there is one thing that is overlooked. Say you scroll down about 5 or 6 lines down ( slow or fast ) you also now lose the position of the app that was highlighted previously. Thus needing to scroll back to that position. If you have alot of games or apps in a category that can be a bit of a pain since it will always go back to the beginning.  I appreciate your work and I have also bought the app to contribute to your project. Hopefully we can get some sort of setting in a future update 🥂

**Comment by spocky** [comment]
The issue you're describing (losing previous card position) is not related to this optimization that only prevents network/disk I/O (image loading) while scrolling. The cards are still there, you just can't see them because their thumbnail is not loaded.
This will be fixed in 4.52

**Comment by Yoshi1981** [comment]
It's true that the apps are very dragging on the screen and after restarting, the apps logos are only slowly displayed !

Otherwise I don't have anything negative about it, everything is fine

You can set everything you want and like

Thanks

**Comment by spocky** [comment]
An option had been added in the upcoming 4.52 to get the pre 4.50 behavior ("load cards while scrolling")
