### ISSUE TITLE
How to find the black wallpaper bug and fix

### ISSUE THREAD

**Issue by cowballz** [spocky/miproja1#67]
The issue can be resolved by simply pressing the back button at the homescreen, rebooting the device or force closing via settings once you have made your selection

https://youtu.be/IT_0j__aNPI?si=1vFlYqCjbXpLd9YH

**Comment by spocky** [comment]
Thanks, I've fixed it today. The issue seems to be only present on Android 12+ devices (on my CCwGtv), but not before (my Shield was not impacted. As it's my main developpment device, this explains why I couldn't reproduce it) as was due to how the lifecycle of Android objects changed in these versions.
